apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: helloworld-deployment
spec: 
  selector: 
    matchLabels: 
      app: helloworld 
  replicas: 4 
  template: 
    metadata: 
      labels: 
        app: helloworld 
    spec: 
      containers: 
      - name: helloworld 
        image: sagishwartz/final:153 
        ports: 
        - containerPort: 80
